"""
GridGuard — Interactive Environment Setup
Run this once to create your .env file with all required keys.
Usage: python setup_env.py
"""
import os
import sys
import pathlib


ENV_PATH = pathlib.Path(".env")

print("\n" + "=" * 60)
print("  GridGuard - Environment Setup")
print("  This creates your .env file with real API keys")
print("=" * 60 + "\n")
 

if ENV_PATH.exists():
    overwrite = input(".env already exists. Overwrite? (y/N): ").strip().lower()
    if overwrite != "y":
        print("Aborted. Your existing .env is unchanged.")
        sys.exit(0)

print("Press Enter to keep the default value shown in [brackets].\n")

# ── Google Cloud ───────────────────────────────────────────────
print("--- Google Cloud ---")
gcp_project = input("GCP Project ID [grid-guard-507218]: ").strip() or "grid-guard-507218"
gcp_region   = input("GCP Region [us-central1]: ").strip() or "us-central1"

# ── Arize Phoenix ──────────────────────────────────────────────
print("\n--- Arize Phoenix ---")
print("Get your API key at: https://app.phoenix.arize.com -> Settings -> API Keys")
phoenix_key = input("PHOENIX_API_KEY: ").strip()
if not phoenix_key:
    print("[WARN] No Phoenix key entered - traces won't be sent. You can add it later.")

# ── NVD API Key ────────────────────────────────────────────────
print("\n--- NIST NVD API (optional but recommended) ---")
print("Register free key at: https://nvd.nist.gov/developers/request-an-api-key")
nvd_key = input("NVD_API_KEY (press Enter to skip): ").strip()

# ── Write .env ─────────────────────────────────────────────────
env_content = f"""# ============================================================
# GridGuard — Environment Variables
# Generated by setup_env.py — DO NOT COMMIT THIS FILE
# ============================================================

# --- Google Cloud ---
GOOGLE_CLOUD_PROJECT={gcp_project}
GOOGLE_CLOUD_REGION={gcp_region}
GOOGLE_CLOUD_LOCATION={gcp_region}
GOOGLE_GENAI_USE_VERTEXAI=true
GOOGLE_GENAI_USE_ENTERPRISE=1

# --- Arize Phoenix ---
PHOENIX_API_KEY={phoenix_key}
PHOENIX_BASE_URL=https://app.phoenix.arize.com
PHOENIX_PROJECT_NAME=gridguard
GRIDGUARD_ENABLE_PHOENIX_MCP=true

# --- Threat Intelligence APIs ---
NVD_API_KEY={nvd_key}

# --- App Config ---
GRIDGUARD_ENV=development
GRIDGUARD_MODEL=gemini-3-flash-preview
LOG_LEVEL=INFO
PORT=8080
"""

ENV_PATH.write_text(env_content, encoding="utf-8")
print(f"\n[OK] .env created successfully")

# Verify key packages
print("\n--- Verifying installation ---")
try:
    from google.adk.agents import LlmAgent
    print("[OK] google-adk")
except ImportError:
    print("[ERROR] google-adk missing - run: pip install -r requirements.txt")

try:
    from phoenix.otel import register
    print("[OK] arize-phoenix-otel")
except ImportError:
    print("[ERROR] arize-phoenix-otel missing - run: pip install -r requirements.txt")

try:
    from fastapi import FastAPI
    print("[OK] fastapi")
except ImportError:
    print("[ERROR] fastapi missing - run: pip install -r requirements.txt")

if phoenix_key:
    print(f"\n[OK] Phoenix traces will appear at:")
    print("  Open the exact workspace/project link shown by your Phoenix account")

print("\n" + "=" * 60)
print("  Setup complete! Run: python main.py")
print("  Dashboard: http://localhost:8080")
print("=" * 60 + "\n")


